version : '3.8'

services:
  db:
    image: postgres:15
    container_name: coupon_db
    restart: always
    environment:
        POSTGRES_DB: coupon_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        - DB_URL=jdbc:postgresql://db:5432/coupon_db
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
      depends_on:
        - db
  

volumes:
  db_data: